In [1]:
import pandas as pd
import json
import requests
import os

In [3]:
url = 'https://www.twse.com.tw/rwd/zh/afterTrading/BFT41U?date=20240812&selectType=ALLBUT0999&response=json&_=1723714334350'
data = requests.get(url).text
data = json.loads(data)

In [13]:
ohlcv_data = pd.DataFrame(data['data'])
ohlcv_data = ohlcv_data[: -1]
time_series = pd.DataFrame([data['date']] * len(ohlcv_data))
fetch_df = pd.concat([ohlcv_data, time_series], axis = 1)
fetch_df.columns = ['symbal', 'name', 'volume', 'count', 'amount', 'close', 'last_display_buy_volume', 'last_display_sell_volume', 'datetime']
fetch_df

,symbal,name,volume,count,amount,close,last_display_buy_volume,last_display_sell_volume,datetime
0,0050,元大台灣50,43,41,"7,656,150",178.05,0,50,20240812
1,0051,元大中型100,0,0,0,78.40,2,0,20240812
2,0052,富邦科技,10,2,"1,737,000",173.70,0,371,20240812
3,0053,元大電子,0,0,0,95.50,3,0,20240812
4,0055,元大MSCI金融,1,1,"28,360",28.36,19,0,20240812
...,...,...,...,...,...,...,...,...,...
1230,9944,新麗,0,0,0,20.60,6,0,20240812
1231,9945,潤泰新,18,18,"870,300",48.35,66,0,20240812
1232,9946,三發地產,1,1,"38,500",38.50,2,0,20240812
1233,9955,佳龍,10,5,"356,000",35.60,38,0,20240812
1234,9958,世紀鋼,5,5,"1,002,500",200.50,48,0,20240812

In [14]:
fetch_df.to_csv('/Users/xinc./Documents/GitHub/Quant_idea/data/2024定價交易.csv')